1) Version of NumPy

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.19.5'

2) Version of Pandas

In [3]:
pd.__version__

'1.2.1'

In [8]:
data = pd.read_csv('data.csv')
data = pd.DataFrame(data)
data.head()


Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

What's the average price of BMW cars in the dataset?

In [13]:
bmw_data = data[data['Make'] == 'BMW']
bmw_data['MSRP'].mean()


61546.76347305389

Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [29]:
engine_hp = data[data['Year'] >= 2015]['Engine HP']
engine_hp.isna().sum()


51

In [33]:
mean_hp_before = engine_hp.mean()
mean_hp_after = engine_hp.fillna(mean_hp_before).mean()
print(round(mean_hp_before))
print(round(mean_hp_after))


273
273


Question 6

In [86]:
rr_data = data[data['Make'] == 'Rolls-Royce']
tx = rr_data[["Engine HP", "Engine Cylinders", "highway MPG"]]
tx
X = tx.drop_duplicates()
X = X.values
print(X)
XTX = X.T.dot(X)
np.linalg.inv(XTX).sum()


[[325.   8.  15.]
 [563.  12.  19.]
 [563.  12.  21.]
 [563.  12.  20.]
 [322.  12.  15.]
 [453.  12.  19.]
 [624.  12.  21.]]


0.03221232067748617

Questions 7

In [85]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
w = np.linalg.inv(XTX).dot(X.T).dot(y)
w


array([ 0.19989598, 31.02612262, 31.65378877])