<a href="https://colab.research.google.com/github/arpitchittora/arpit-ml-zzomcamp-v2/blob/master/week-9/ML_zoomcamp_week_9_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Download Model

In [4]:
!wget https://github.com/alexeygrigorev/large-datasets/releases/download/dogs-cats-model/dogs_cats_10_0.687.h5

--2021-12-01 16:38:33--  https://github.com/alexeygrigorev/large-datasets/releases/download/dogs-cats-model/dogs_cats_10_0.687.h5
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github-releases.githubusercontent.com/426348925/f4f8406c-b1cd-4377-94a0-8a89b6f826bd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20211201%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20211201T163833Z&X-Amz-Expires=300&X-Amz-Signature=69428c2605f5fab8666784502e2f22d528b1f88ab7eb0e242b7e54235bcfe0e1&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=426348925&response-content-disposition=attachment%3B%20filename%3Ddogs_cats_10_0.687.h5&response-content-type=application%2Foctet-stream [following]
--2021-12-01 16:38:33--  https://github-releases.githubusercontent.com/426348925/f4f8406c-b1cd-4377-94a0-8a89b6f826bd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-A

In [ ]:
!python -V

Python 3.7.12


In [6]:
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.applications.xception import preprocess_input

In [8]:
model = keras.models.load_model('dogs_cats_10_0.687.h5')

In [ ]:
path = './pexels-evg-culture-1170986.jpg'

In [ ]:
img = load_img(path, target_size=(150, 150))

In [ ]:
x = np.array(img)
X = np.array([x])

In [ ]:
X = preprocess_input(X)
pred = model.predict(X)

In [ ]:
pred

array([[0.7861396]], dtype=float32)

In [ ]:
classes = [
    'cat',
    'dog'
]

In [ ]:
dict(zip(classes, pred[0]))

{'cat': 0.7861396}

Above model is working correctly. Now we will convert into TF-lite version.

**Convert Keras to TF-Lite**

In [9]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)

tflite_model = converter.convert()

with open('dogs-cats-model.tflite', 'wb') as f_out:
    f_out.write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmpti9werkz/assets


**Question 1**

Now convert this model from Keras to TF-Lite format.

What's the size of the converted model?



In [ ]:
!ls -lh

total 129M
-rw-r--r-- 1 root root  86M Nov 25 07:02 dogs_cats_10_0.687.h5
-rw-r--r-- 1 root root  43M Nov 30 01:29 dogs-cats-model.tflite
-rw-r--r-- 1 root root 408K Nov 30 01:21 pexels-evg-culture-1170986.jpg
drwxr-xr-x 1 root root 4.0K Nov 18 14:36 sample_data


Answer: ***43MB***

**Question 2**

To be able to use this model, we need to know the index of the input and the index of the output.

What's the output index for this model?

In [2]:
import tensorflow.lite as tflite
import numpy as np

In [10]:
interpreter = tflite.Interpreter(model_path="./dogs-cats-model.tflite")
interpreter.allocate_tensors()

input_index = interpreter.get_input_details()[0]['index']
output_index = interpreter.get_output_details()[0]['index']

In [11]:
print(input_index,output_index)

0 13


**Removing TF dependency**

Preparing the image

In [ ]:
pip install pillow

In [12]:
from io import BytesIO
from urllib import request
import requests

from PIL import Image

In [13]:
def download_image(url):
    with request.urlopen(url) as resp:
        buffer = resp.read()
    stream = BytesIO(buffer)
    img = Image.open(stream)
    return img


def prepare_image(img, target_size):
    if img.mode != 'RGB':
        img = img.convert('RGB')
    img = img.resize(target_size, Image.NEAREST)
    return img

In [14]:
new_path = 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Pug_600.jpg'

In [15]:
image = download_image(new_path)
image = prepare_image(image,(150,150))

In [16]:
x = np.array(image, dtype='float32')
X = np.array([x])

# Preprocess the image 
X = np.float32(X*(1./255))


In [17]:
X

array([[[[0.7058824 , 0.7725491 , 0.7490196 ],
         [0.69411767, 0.7607844 , 0.7294118 ],
         [0.6313726 , 0.69803923, 0.6666667 ],
         ...,
         [0.76470596, 0.85098046, 0.83921576],
         [0.68235296, 0.74509805, 0.74509805],
         [0.6745098 , 0.7686275 , 0.77647066]],

        [[0.5254902 , 0.5921569 , 0.5686275 ],
         [0.7372549 , 0.80392164, 0.7803922 ],
         [0.60784316, 0.6745098 , 0.6431373 ],
         ...,
         [0.79215693, 0.86666673, 0.8588236 ],
         [0.6313726 , 0.7019608 , 0.6392157 ],
         [0.78823537, 0.87843144, 0.854902  ]],

        [[0.6862745 , 0.7490196 , 0.7372549 ],
         [0.61960787, 0.6862745 , 0.6627451 ],
         [0.64705884, 0.7137255 , 0.68235296],
         ...,
         [0.6       , 0.65882355, 0.64705884],
         [0.627451  , 0.69411767, 0.654902  ],
         [0.7058824 , 0.7960785 , 0.7725491 ]],

        ...,

        [[0.5803922 , 0.61960787, 0.58431375],
         [0.4901961 , 0.5254902 , 0.5058824 ]

In [18]:
pred = model.predict(X)

In [20]:
classes = [
    'cat',
    'dog'
]

In [21]:
dict(zip(classes, pred[0]))

{'cat': 0.7704914}

In [ ]:
pred

array([[0.9703119]], dtype=float32)

In [22]:
interpreter.set_tensor(input_index, X)
interpreter.invoke()
preds = interpreter.get_tensor(output_index)

In [25]:
preds[0].tolist()

[0.7704910635948181]